# Streamlit secrets.toml example

# [general] section for app-wide secrets
[general]
secret_key = "your_streamlit_secret_key_here"

# [database] section for DB credentials (if any)
[database]
user = "your_db_user"
password = "your_db_password"
host = "localhost"
port = "5432"
dbname = "your_db_name"

# [api_keys] section for any API keys
[api_keys]
google = "your_google_api_key"
kaggle_username = "your_kaggle_username"
kaggle_key = "your_kaggle_key"

# [other] section for any other secrets or config
[other]
debug = false